module.exports = {
  apps: [{
    name: 'api',
    script: 'src/api/dist/index.js',
    cwd: '.',
    watch: false,
    env: {
      NODE_ENV: 'development',
    },
    env_production: {
      NODE_ENV: 'production',
    },
    error_file: '/var/spool/certM3/logs/api-error.log',
    out_file: '/var/spool/certM3/logs/api-out.log',
    log_file: '/var/spool/certM3/logs/api-combined.log',
    time: true,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  },
  {
    name: 'certm3-app',
    script: 'src/mw/bin/certm3-app',
    cwd: '.',
    watch: false,
    env: {
      NODE_ENV: 'production',
    },
    error_file: '/var/spool/certM3/logs/certm3-app-error.log',
    out_file: '/var/spool/certM3/logs/certm3-app-out.log',
    log_file: '/var/spool/certM3/logs/certm3-app-combined.log',
    time: true,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    max_memory_restart: '1G',
  },
  {
    name: 'certm3-signer',
    script: 'src/mw/bin/certm3-signer',
    cwd: '.',
    watch: false,
    env: {
      NODE_ENV: 'production',
    },
    error_file: '/var/spool/certM3/logs/certm3-signer-error.log',
    out_file: '/var/spool/certM3/logs/certm3-signer-out.log',
    log_file: '/var/spool/certM3/logs/certm3-signer-combined.log',
    time: true,
    merge_logs: true,
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    max_memory_restart: '1G',
  }],
}; 
