# Logging configuration
# Global log level (debug, info, warn, error)
log_level: debug  
log_file: /var/log/certM3/mw/app.log
# Enable verbose logging to stdout
verbose: true  

# App server configuration
app_server:
  listen_addr: ":8080"
  frontend_baseurl: "https://urp.ogt11.com/app"
  backend_baseurl: "https://urp.ogt11.com/api"
# Will be loaded from /var/spool/certM3/mw/JWT-secret
  jwt_secret: ""  
  rate_limit_per_ip: 100
  metrics_enabled: true
  metrics_path: "/metrics"
  metrics_timeout: 5s
  test_email_dir: "/var/spool/certM3/test-emails/"

# Signer configuration
signer:
  socket_path: "/var/spool/certM3/signer/signer.sock"
  ca_cert_path: "../../CA/certs/ca-cert.pem"
  ca_key_path: "../../CA/private/ca-key.pem"
  group_extension_oid: "1.3.6.1.4.1.10049.2"  
  # Groups extension OID
  # username_extension_oid removed - username is now only in CN 
