#!/bin/bash

# Quick start template for CertM3 CA setup
# This script shows the typical workflow for setting up CAs

echo "CertM3 CA Setup Quick Start"
echo "=========================="
echo ""
echo "This template shows the typical workflow for setting up CAs."
echo "Run these commands from the CA-mgmt/root directory:"
echo ""
echo "1. Create root CA:"
echo "./create-root-ca.sh"
echo ""
echo "2. Create intermediate CAs (run from CA-mgmt/intermediate):"
echo "./create-user-ca.sh"
echo "./create-api-ca.sh"
echo "./create-db-ca.sh"
echo ""
echo "3. Sign intermediate CAs (run from CA-mgmt/root):"
echo ""
echo "With YubiKey:"
echo "./yubikey-sign-intermediate-ca.sh ../../CA/intermediate/user-ca/certs/ca.csr \\"
echo "    ../../CA/intermediate/user-ca/certs/ca.crt 1825"
echo ""
echo "With OpenSSL:"
echo "./OSSL-sign-intermediate-ca.sh ../../CA/intermediate/user-ca/certs/ca.csr \\"
echo "    ../../CA/intermediate/user-ca/certs/ca.crt 1825"
echo ""
echo "4. Create service certificates:"
echo "mkdir -p ../../CA/services/database"
echo "openssl req -new -keyout ../../CA/services/database/server.key \\"
echo "    -out ../../CA/services/database/server.csr \\"
echo "    -subj '/CN=database.example.com'"
echo ""
echo "openssl x509 -req -in ../../CA/services/database/server.csr \\"
echo "    -out ../../CA/services/database/server.crt \\"
echo "    -CA ../../CA/intermediate/database-ca/certs/ca.crt \\"
echo "    -CAkey ../../CA/intermediate/database-ca/private/ca.key \\"
echo "    -CAcreateserial -days 365"
echo ""
echo "5. Set proper permissions:"
echo "chmod 600 ../../CA/**/*.key"
echo "chmod 644 ../../CA/**/*.crt"
echo ""
echo "6. Check expiration dates:"
echo "./monitoring/check-expiration.sh" 